/**
 * Ctrip (携程) flight search client.
 *
 * Strategy (tried in order):
 *   1. CDP scraper subprocess — local only, requires Chrome on port 9223
 *   2. (Future) Cloud browser proxy — Browserless.io / ScrapingBee
 *
 * The direct batchSearch API at /international/search/api/search/batchSearch
 * requires an x-ctx-fvpc encrypted header generated by Ctrip's client-side JS.
 * Direct HTTP calls return status=0 with 0 results without this header.
 * Reverse-engineering the encryption is impractical for now.
 *
 * On Netlify (no Chrome), this source returns empty results.
 */

import { spawn } from 'child_process';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = (() => {
  try { return dirname(fileURLToPath(import.meta.url)).replace('/sources', ''); }
  catch { return process.cwd(); }
})();

const CDP_PORT = 9223;

export const meta = {
  id: 'ctrip',
  name: '携程',
  requiresChrome: true,
  provides: ['price'],
};

/**
 * Check if Chrome CDP is reachable.
 */
async function isChromeAvailable() {
  try {
    const resp = await fetch(`http://localhost:${CDP_PORT}/json/version`);
    return resp.ok;
  } catch {
    return false;
  }
}

/**
 * Search Ctrip flights using the CDP scraper subprocess.
 */
function searchViaCdp(origin, destination, date) {
  return new Promise((resolve) => {
    const proc = spawn('python3', [
      '-u', join(__dirname, 'cdp_scraper.py'),
      origin, destination, date, '--json',
    ], {
      cwd: __dirname,
      env: {
        ...process.env,
        NO_PROXY: 'localhost,127.0.0.1,::1',
        PYTHONIOENCODING: 'utf-8',
        PYTHONUNBUFFERED: '1',
      },
      timeout: 45000,
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (data) => { stdout += data.toString(); });
    proc.stderr.on('data', (data) => { stderr += data.toString(); });

    proc.on('close', (code) => {
      if (stderr) {
        const lines = stderr.split('\n').filter(l => l.trim());
        const relevant = lines.filter(l =>
          l.includes('[Ctrip]') || l.includes('Error') || l.includes('Traceback')
        );
        if (relevant.length > 0) console.log('Ctrip CDP:', relevant.join('\n'));
      }
      try {
        // CDP scraper wraps JSON with __JSON_START__ / __JSON_END__ markers
        const startMarker = '__JSON_START__';
        const endMarker = '__JSON_END__';
        const startIdx = stdout.indexOf(startMarker);
        const endIdx = stdout.indexOf(endMarker);
        if (startIdx >= 0 && endIdx > startIdx) {
          const jsonStr = stdout.slice(startIdx + startMarker.length, endIdx).trim();
          const parsed = JSON.parse(jsonStr);
          resolve(parsed.ctrip || []);
        } else {
          // Fallback: try regex
          const match = stdout.match(/\{\s*"ctrip"[\s\S]*\}\]\s*\}/);
          if (match) {
            const parsed = JSON.parse(match[0]);
            resolve(parsed.ctrip || []);
          } else {
            resolve([]);
          }
        }
      } catch (err) {
        console.error('Ctrip CDP parse error:', err.message);
        resolve([]);
      }
    });

    proc.on('error', (err) => {
      console.error('Ctrip CDP start error:', err.message);
      resolve([]);
    });
  });
}

/**
 * Search Ctrip flights.
 * @param {{ origin: string, destination: string, date: string }} params
 * @returns {Promise<Array>}
 */
export async function search(params) {
  const chromeOk = await isChromeAvailable();
  if (chromeOk) {
    console.log('Ctrip: using CDP scraper (Chrome available)');
    return searchViaCdp(params.origin, params.destination, params.date);
  }

  console.log('Ctrip: Chrome not available, returning 0 results');
  return [];
}

export async function isAvailable() {
  if (process.env.NETLIFY) return false;
  return isChromeAvailable();
}
